### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(css_file)

### ISSUE THREAD

**Issue by rafaelreuber** [kxxoling/markdown2pdf#17]
I just got the following error when use the markdown2pdf.

```
 [reuber@stormy hive-api]$ md2pdf ENDPOINTS.md --theme=github
Traceback (most recent call last):
  File "/home/reuber/envs/hive-api/bin/md2pdf", line 11, in <module>
    load_entry_point('Markdown2PDF==0.1.4', 'console_scripts', 'md2pdf')()
  File "/home/reuber/envs/hive-api/lib64/python3.8/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/reuber/envs/hive-api/lib64/python3.8/site-packages/pkg_resources/__init__.py", line 2859, in load_entry_point
    return ep.load()
  File "/home/reuber/envs/hive-api/lib64/python3.8/site-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/home/reuber/envs/hive-api/lib64/python3.8/site-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/reuber/envs/hive-api/lib64/python3.8/site-packages/markdown2pdf/__init__.py", line 20
    print css_file
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(css_file)?
```

It' seems the pypi version is an old version.

**Comment by Sanil2108** [comment]
You could try https://pypi.org/project/markdown2pdf3/

**Comment by leinss** [comment]
markdown2pdf3   0.2.3
```
md2pdf README.md

Traceback (most recent call last):
  File "c:\users\tol\miniconda3\envs\smt\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\tol\miniconda3\envs\smt\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\tol\Miniconda3\envs\smt\Scripts\md2pdf.exe\__main__.py", line 4, in <module>     
  File "c:\users\tol\miniconda3\envs\smt\lib\site-packages\markdown2pdf3\__init__.py", line 3, in 
<module>
    from .main import convert_markdown_to_pdf
  File "c:\users\tol\miniconda3\envs\smt\lib\site-packages\markdown2pdf3\main.py", line 3, in <module>
    import pypandoc
ModuleNotFoundError: No module named 'pypandoc'
```

**Comment by Waples** [comment]
same here....

**Comment by Sammeeey** [comment]
same here...

**Comment by sergenti** [comment]
+1

**Comment by saiteja21** [comment]
still the same, I guess this is not fixed
