### ISSUE TITLE
python 3 doesn't supported?

### ISSUE THREAD

**Issue by itJunky** [kxxoling/markdown2pdf#8]
```
Traceback (most recent call last):
  File "./env/bin/md2pdf", line 7, in <module>
    from markdown2pdf import main
  File "/home/alp/wrk/visyond.com/repos/environment_root/util/checkbranch/env/lib/python3.6/site-packages/markdown2pdf/__init__.py", line 20
    print css_file
                 ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print css_file)?
```

**Comment by kxxoling** [comment]
No, it does not. You could clone it and did a little work to fix it.

**Comment by jfthuong** [comment]
I have created such fork and done a Pull Request: https://github.com/jfthuong/markdown2pdf
